### ISSUE TITLE
Multicast Feedback

### ISSUE THREAD

**Issue by TheCrab-xx** [sunaoka/push-notifications-php#2]
Hi, could you please help me to understand how to implement feedback with multicast message?
Thank you

**Comment by sunaoka** [comment]
Please be specific about what you don't understand.

**Comment by TheCrab-xx** [comment]
I'm using this approach, but I receive "540 Gateway Timeout"

$batch_of = 500;
$batch = array_chunk($deviceTokens, $batch_of, true);

foreach ($batch as $tokens) {

    $driver = new APNs\Token($options);
    $pusher = new Pusher($isSandbox);
    $feedback = $pusher->to($tokens)->send($driver);

    foreach ($deviceTokens as $token) {
      if($feedback->isSuccess($token)){
        $result['success'][] = array("token_success"=>$token);
      }else{
        $result['failed'][] = array("error"=>$feedback->failure($token));
      }
    }
  echo $result;
}
