### ISSUE TITLE
Would this work for SIP/VoIP on Kamailio/Opensips

### ISSUE THREAD

**Issue by hasanr68** [sunaoka/push-notifications-php#3]
Hi there.

Apologies for raising a ticket. Was unsure how to get in touch. I would like to implement this with a SIP proxy (Opensips) to send push notifications to APNS + Firebase. Can your project be used in this scenario?

Thanks.

**Comment by sunaoka** [comment]
I have never done this before so I do not know.
We are sorry.

**Comment by hasanr68** [comment]
Not a problem. Thx for responding, but it would be possible to send notifications to APNS + Firebase?

**Comment by sunaoka** [comment]
> but it would be possible to send notifications to APNS + Firebase?

Yes.
